the-difference-engine/svp-chicago

Gemfile
Gemfile.lock
Procfile
config/puma.rb

Added puma

---

app/controllers/lois_controller.rb
app/models/answer.rb
app/models/loi.rb
app/models/question.rb
app/views/lois/edit.html.erb
app/views/lois/index.html.erb
app/views/lois/show.html.erb
app/views/users/index.html.erb
db/migrate/20160411022833_create_answers.rb
db/schema.rb
spec/models/answer_spec.rb

@OliveBobbie @santamariaa Hi Team. I made another pull request.  This just adds to what I did yesterday with the LOI form. See you tonight.

Added to the LOI controller and form

---

app/assets/javascripts/lois.coffee
app/assets/stylesheets/lois.scss
app/controllers/lois_controller.rb
app/models/answer.rb
app/models/challenge.rb
app/models/fte.rb
app/models/loi.rb
app/views/lois/new.html.erb
app/views/lois/show.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
db/migrate/20160415005204_create_challenges.rb
db/migrate/20160415005730_create_ftes.rb
db/schema.rb
spec/models/challenge_spec.rb
spec/models/fte_spec.rb

@OliveBobbie @santamariaa Hey guys, I made a lot of progress on the LOI form and the corresponding show page.  We can review this code together tonight. See you later.

Added Elements to LOI new and show

---

app/assets/stylesheets/lois.css.scss
app/controllers/lois_controller.rb
app/views/landings/home.html.erb
app/views/lois/new.html.erb
app/views/lois/show.html.erb

worked on ratings (added functionality to loi show page)

Zeina landingpage2

---

app/assets/stylesheets/lois.css.scss
app/views/lois/show.html.erb

fixed ratings on loi page to be shallower and wider to accommodate smaller resolutions

Zeina ratingsfix

---

app/assets/stylesheets/ratings.scss
app/views/questions/edit.html.erb
app/views/questions/index.html.erb

Edited the index and edit files from questions and ratings.css to center some text

as an admin or super admin you cannot edit the organization question

---

app/assets/javascripts/invite_maxes.coffee
app/assets/stylesheets/invite_maxes.scss
app/assets/stylesheets/lois.css.scss
app/assets/stylesheets/style.css.scss
app/controllers/invite_maxes_controller.rb
app/controllers/lois_controller.rb
app/controllers/ratings_controller.rb
app/helpers/invite_maxes_helper.rb
app/models/invite_max.rb
app/views/invite_maxes/edit.html.erb
app/views/lois/index.html.erb
app/views/lois/show.html.erb
app/views/ratings/index.html.erb
app/views/users/index.html.erb
config/routes.rb
db/migrate/20160630233814_create_invite_maxes.rb
db/schema.rb
spec/controllers/invite_maxes_controller_spec.rb
spec/factories/invite_maxes.rb
spec/helpers/invite_maxes_helper_spec.rb
spec/models/invite_max_spec.rb

Made some tweaks to how admins rate lois and what loi index page looks like once one has been rated, and made a table/controller for invite maximums (ie an admin's ability to hit YES at q5). A super admin can change that number.

Zeina ratingfix

---

app/assets/javascripts/rfps_ctrl.js
app/controllers/api/v1/rfp_sections_controller.rb
app/views/rfps/new.html.erb
config/routes.rb

This PR relates to Trello card #42 - it's the completion of the RFP form - sans any styling.

can submit rfp form

---

app/assets/stylesheets/rfps.css.scss
app/assets/stylesheets/rfps.scss
app/views/rfps/new.html.erb

@paulyk1983 @danasblack 
I added a little bit of bootstrap style just to make the form more readable.

added a little styling to the rfp-new form

---

app/assets/javascripts/edit_lois_ctrl.js
app/controllers/api/v1/lois_controller.rb
app/views/lois/edit.html.erb

@paulyk1983 @danasblack Hey guys, here's another PR addressing a bug I found when a user tries to edit a partially filled out LOI form.

fixed a bug with updating the challenge section of the loi form

---

app/controllers/rfps_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb

@dchu4 @danasblack @paulyk1983 I fixed the superadmin access. Check it out.

added superadmin can view rfp

---

db/migrate/20160615220345_create_rfp_answers.rb

@paulyk1983 Hey Paul, here's the missing migration file.
If you have a chance, why don't you pull this branch down before you merge it and see it you can run the migration and thus hopefully be able to submit a form.

missing migration file

---

app/controllers/rfps_controller.rb

@paulyk1983 Hey paul, can you review this for me?Thanks  --Aaron

fixed RFP controller

---

app/controllers/rfps_controller.rb
app/models/rfp.rb
app/views/api/v1/rfps/index.json.jbuilder
app/views/layouts/application.html.erb
app/views/rfps/index.html.erb

@laurenjoyce @dchu4 Check out my pr! Thanks  --Aaron

rfps nav button for admin and super admins

---

app/assets/javascripts/rfps_ctrl.js

@paulyk1983 
Hey Paul, I rearranged the angular a bit to make sure it didn't break other modules.
Can you see if this will still work on your local?

Svp51 fix angular for rfp form

---

app/assets/javascripts/rfps_ctrl.js
app/controllers/api/v1/rfp_sections_controller.rb
app/views/rfps/new.html.erb
db/migrate/20160817193327_add_submitted_to_rfp.rb
db/schema.rb

@danasblack @heydanhey @dchu4 @AaronOoooo @laurenjoyce

59 save rfp

---

app/assets/javascripts/edit_lois_ctrl.js
app/assets/javascripts/forms_ctrl.js
app/assets/stylesheets/lois.css.scss
app/views/lois/edit.html.erb
app/views/lois/new.html.erb
app/views/users/show.html.erb

Svp67 bugfix

---

app/assets/javascripts/questions.coffee
app/controllers/api/v1/questions_controller.rb
app/controllers/questions_controller.rb
app/models/section.rb
app/views/questions/index.html.erb
db/migrate/20160819222539_add_is_active_to_questions.rb
db/schema.rb

@dchu4 @paulyk1983 @danasblack @AaronOoooo @laurenjoyce 
[SVP71-As a super-admin, I will be able to make an LOI question inactive.](https://trello.com/c/wspSArje/71-as-a-super-admin-i-will-be-able-to-make-an-loi-question-inactive)

Svp71 make loi questions inactive

---

app/views/layouts/application.html.erb

@dchu4 @paulyk1983 @danasblack @AaronOoooo @laurenjoyce 
Hi Team - The Navbar was getting a little crowded - and since we're going to roll out the LOI functionality before the RFP is finished, I thought it made sense to separate the links. Check it out and let me know your thoughts?
[SVP80-Restyled Navbar to separate LOI links from RFP links.](https://trello.com/c/wcurOezg/80-restyled-navbar-to-separate-loi-links-from-rfp-links)

restyled navbar

---

app/controllers/api/v1/lois_controller.rb
app/controllers/api/v1/rfp_sections_controller.rb
app/controllers/api/v1/rfps_controller.rb
app/controllers/api/v1/sections_controller.rb
app/controllers/invite_maxes_controller.rb
app/controllers/lois_controller.rb
app/controllers/questions_controller.rb
app/controllers/ratings_controller.rb
app/controllers/rfp_questions_controller.rb
app/controllers/rfp_sections_controller.rb
app/controllers/rfps_controller.rb
app/models/rfp.rb
app/models/user.rb
app/views/users/show.html.erb
config/environments/development.rb

@paulyk1983 @danasblack @dchu4 @AaronOoooo @laurenjoyce 
Just went through and added the appropriate `before_actions` to make sure access was verified.
Also, added logic so only one RFP form can be submitted per user.
PS. My text editor auto-replaced blank spaces at line ends - so most of the changes are related to that - sorry.
[SVP56-Security Issues](https://trello.com/c/V4DpFCps/56-security-checks-as-a-visitor-who-is-not-logged-in-i-will-not-be-able-to-access-any-unauthorized-page-as-a-user-who-is-logged-in-)

Svp56 security

---

app/controllers/api/v1/lois_controller.rb
app/views/loi_submitted_email_to_admin.html.erb

@danasblack @heydanhey @dchu4 @laurenjoyce @AaronOoooo This is ready to be reviewed and then merged. The link in the email is currently set to the heroku demo server. When testing this locally, change domain from https://demo-svp-chicago.herokuapp.com to http://localhost:3000, when testing on qa, change to https://qa-svp-chicago.herokuapp.com

Added feature that sends email to admin when user submits an loi form

---

app/controllers/api/v1/lois_controller.rb
app/controllers/lois_controller.rb
app/views/lois/edit.html.erb
app/views/lois/loi_submitted_email_to_admin.html.erb
app/views/lois/show.html.erb

@dchu4 @heydanhey @AaronOoooo @laurenjoyce This sets it so only a super-admin can edit an already submitted LOI form. Regular users should not be able to do this because it might affect how the admins would rate that LOI.

61 resubmit loi

---

.gitignore
app/views/loi_submitted_email_to_admin.html.erb
app/views/submission_email.html.erb

I made this branch to prevent confusion in git and github about the email templates since the app is currently programmed to re-write those files.

added email template files to git ignore.

---

app/assets/javascripts/lois_index_ctrl.js

Fix for the average rating sort.

updated angular controller to correct sortBy function

---

app/controllers/lois_controller.rb

[SVP56](https://trello.com/c/V4DpFCps/56-security-checks-as-a-visitor-who-is-not-logged-in-i-will-not-be-able-to-access-any-unauthorized-page-as-a-user-who-is-logged-in-)

updated loi check for user

---

app/assets/javascripts/lois_index_ctrl.js
app/assets/javascripts/ratings_ctrl.js
app/views/lois/index.html.erb
app/views/ratings/index.html.erb

A lot of the red is indentation @danasblack @heydanhey @paulyk1983 @laurenjoyce @AaronOoooo

Glyphicon fix

---

app/assets/stylesheets/lois.css.scss
app/views/lois/show.html.erb

Got rid of the label tags and change Potential SVP Impact to Potential Impact to make the glyphicons fit in nicely. Unsure if that was ok.

Svp74 revision

---

app/views/lois/loi_submitted_email_to_admin.html.erb

deleted file @heydanhey @paulyk1983 @AaronOoooo @laurenjoyce

deleted the specified file

---

app/assets/javascripts/forms_ctrl.js
app/views/lois/new.html.erb

added validation to questions with text fields

---

app/controllers/api/v1/invited_lois_controller.rb
app/views/loi_acceptance_email.html.erb

Personalized LOI RFP acceptance email.

Svp85 update email

---

app/views/lois/new.html.erb

Fix for validation

---

app/views/lois/new.html.erb

second fix

---

app/assets/stylesheets/landings.css.scss
app/views/layouts/application.html.erb
app/views/loi_submitted_email_to_admin.html.erb

Easy fix! @heydanhey @dchu4 @AaronOoooo

94 minor changes

---

app/views/devise/registrations/new.html.erb

changed copy on sign-in page

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/rollbar.rb

I've added rollbar (an Airbrake substitute) and tested it on QA.

Svp97 add error alerts

---

app/controllers/rfp_questions_controller.rb
app/controllers/rfps_controller.rb
app/views/api/v1/rfp_sections/index.json.jbuilder
app/views/questions/index.html.erb
app/views/rfp_questions/index.html.erb
app/views/rfps/new.html.erb
config/routes.rb
db/migrate/20160927001535_add_is_active2_rfp_questions.rb
db/schema.rb

@AaronOoooo Could you please review this branch?

Svp72 rvp status activity

---

app/views/devise/sessions/new.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb

@dchu4 @JohnJasonFisher @cbjoseph Please review the forgot password function on the login page.

Svp66 forgot login password

---

app/assets/javascripts/rfps_ctrl.js
app/controllers/api/v1/attachments_controller.rb
app/controllers/api/v1/rfp_sections_controller.rb
app/controllers/rfps_controller.rb
app/views/rfps/show.html.erb
db/migrate/20161011000223_add_doc_type_to_attachments.rb
db/schema.rb

Made a doc_type in the attachments model so that doc_type could display on rfps show page and then added icons for the attachments on the show page.

104 rf pshow

---

app/controllers/api/v1/rfp_sections_controller.rb
app/views/rfps/new.html.erb

Fixed divs so multiple inputs showed up

104 fix rfp new

---

app/controllers/api/v1/rfp_sections_controller.rb
app/models/rfp_section.rb
app/views/api/v1/rfp_sections/index.json.jbuilder

We fixed the active for rfp sections status so that only true questions pop up.

fixed the status for active rfp questions

---

app/assets/javascripts/lois_index_ctrl.js
app/controllers/api/v1/lois_controller.rb
app/controllers/lois_controller.rb
app/views/api/v1/lois/index.json.jbuilder
app/views/lois/index.html.erb
db/migrate/20161026231013_change_status_from_lois.rb
db/migrate/20161027013700_change_default_reject_in_lois.rb
db/migrate/20161027235011_lois_reject_default2false.rb
db/schema.rb

Created a reject button. Wrote logic in angular lois index controller, to have the loi spliced from an array.

Loi rejection button

---

app/views/rfps/new.html.erb

Deadline updated to 2017. @heydanhey

Update deadline to 2017

---

app/assets/javascripts/lois_index_ctrl.js
app/controllers/api/v1/lois_controller.rb
db/schema.rb

Fixed the reject button so complies with null and false

fixed reject button to work with null

---

app/assets/stylesheets/lois.css.scss
app/controllers/ratings_controller.rb
app/views/api/v1/ratings/index.json.jbuilder
app/views/lois/show.html.erb
app/views/ratings/index.html.erb
app/views/rfps/index.html.erb
db/migrate/20161108004206_add_comments_to_ratings.rb
db/migrate/20161108004718_change_comments_datatype.rb
db/schema.rb

Please review. Thanks  --Aaron

Svp113 add comments to ratings

---

app/controllers/rfps_controller.rb
app/views/lois/show.html.erb

Very minor update that Colleen requested.

Svp update loi text

---

app/assets/javascripts/rfps_ctrl.js
app/controllers/rfps_controller.rb
app/models/rfp.rb
app/views/lois/show.html.erb
app/views/users/show.html.erb

Please check out...changed text on Ratings tab
@JohnJasonFisher @dchu4

Update LOI Rating Text

---

app/controllers/rfp_ratings_controller.rb
app/views/rfp_ratings/_form.html.erb
app/views/rfp_ratings/new.html.erb
db/migrate/20161129012040_remove_q13.rb
db/migrate/20161129013129_reorder_rfp_ratings1.rb
db/migrate/20161129021247_rfp_ratings_change_test.rb
db/migrate/20161129021538_rfp_ratings_remove_title.rb
db/schema.rb

This branch will fixes many small mistakes.
1. There was a problem with the database for rfp_scores. q13 is no longer a column under rfp_ratings
2. _form under rfp_ratings was changed, there were some typos
3. placeholders under _form where changed too.

Hot fix rfp scores

---

app/views/api/v1/rfp_ratings/index.json.jbuilder
app/views/rfp_ratings/index.html.erb
db/schema.rb

-Changes api/v1/rfp_ratings to include the invited column
-Updates rfp_ratings index page to new scoring tool

130 rfp index new scoring tool

---

app/controllers/rfp_ratings_controller.rb
app/models/rfp_rating.rb

@rwscherrer Hey can you review this please.

fixed bug; added validation for unique rating

---

app/views/users/show.html.erb

BUG: button that allows user to apply for LOI cannot because thinks the deadline is always closed.

click for LOI form toggles now

---

app/controllers/dashboards_controller.rb
app/controllers/lois_controller.rb
app/controllers/users_controller.rb
app/views/users/show.html.erb
db/migrate/20170628215417_add_date_to_dashboard.rb
db/schema.rb

@chijoy This should make it so a super admin can set the date to close the LOI submissions.

add date picker to dashboard

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/edit_lois_ctrl.js
app/assets/javascripts/forms_ctrl.js
app/controllers/lois_controller.rb
app/views/lois/edit.html.erb
app/views/lois/new.html.erb

@chijoy This should address the word count, but I did not but it on all fields. Just the ones that look like they require a lengthy response.  It would be nice when a question is created we could include a filed where the superadmin could add an answer length...then this feature could be more dynamic.

Add word count

---

app/controllers/lois_controller.rb

@chijoy - I forgot to update the edit path. Now a user can submit or edit an LOI Application up until the deadline.  Can you give me access to the new qa and prod sites via heroku?

edit path updated to new loi deadline

---

app/models/loi.rb
app/views/lois/edit.html.erb

@chijoy Just added that `Other` logic to the edit page - a I noticed a bug in the csv, so I had to order the answers.

added other to loi edit and updated csv answer order
